"""init

Revision ID: 445f6b181dd4
Revises: 92f55d07f52a
Create Date: 2020-10-13 15:04:45.980763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '445f6b181dd4'
down_revision = '92f55d07f52a'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
